[package]
name = "spawn_local"
version = "0.1.0"
edition = "2024"

[dependencies]
async-compat = "0.2.5"
reqwest = { version = "0.12.24", features = ["json", "multipart", "blocking"] }
slint = "1.14.1"

[build-dependencies]
slint-build = "1.14.1"
